name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      # - name: Get The Code
      #   uses: actions/checkout@v4
      - name: Greet and Count The Files
        env:
          STUDENT_NAME: ${{ vars.STUDENT_NAME }}
        run: echo "hello, ${{STUDENT_NAME}}"
